image: elixir:1.5

services:
  - postgres:10

variables:
  MIX_ENV: "test"

before_script:
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.reset

test:
  script:
    - mix test
